[Global]
    Name = irc.genesis.local
    Info = genesis_chat demo IRC server
    Listen = 0.0.0.0
    Ports = 6667

[Limits]
    MaxConnections = 50
    MaxJoins = 10

[Options]
    PAM = no

[Channel]
    Name = #genesis
    Topic = genesis_chat construction channel
    Modes = tn
